// LAYOUT DEL APARTADO USUARIOS REGISTRADOS

// Importamos el componente RegisteredUsersNavbar
import RegisteredUsersNavbar from '../../../components/RegisteredUsersNavbar.jsx';

export const metadata = {
  title: 'Registered Users',
  description: 'Generated by create next app',
}

export default function RegisteredUsersLayout({ children }) {
  return (
    <>

        <div className="flex flex-col min-h-screen bg-slate-300">
          
          {/* Añadimos un componente RegisteredUsersNavbar */}
          <RegisteredUsersNavbar></RegisteredUsersNavbar>

          {children}
        </div>
    </>
  );
};