// LAYOUT DEL APARTADO ADMINISTRATION

// Importamos el componente AdministrationNavbar
import AdministrationNavbar from '../../../components/AdministrationNavbar.jsx';

export const metadata = {
  title: 'Administration',
  description: 'Generated by create next app',
}

export default function AdministrationLayout({ children }) {
  return (
    <>

        <div className="flex flex-col min-h-screen bg-slate-300">
          
          {/* Añadimos un componente AdministrationNavbar */}
          <AdministrationNavbar></AdministrationNavbar>

          {children}
        </div>
    </>
  );
};