// LAYOUT DEL APARTADO BUSINESS

// Importamos el componente BusinessNavbar
import BusinessNavbar from '../../../components/BusinessNavbar.jsx';

export const metadata = {
  title: 'Business',
  description: 'Generated by create next app',
}

export default function BusinessLayout({ children, params}) {
  return (
    <>

      <div className="flex flex-col min-h-screen bg-slate-300">

        {/* Añadimos un componente BusinessNavbar y le pasamos el ID del comercio obtenido por params */}
        <BusinessNavbar businessID={params.id} />

        {children}
      </div>
        
    </>
  );
};