import { Inter } from 'next/font/google'
import './globals.css'

// Fuente
const inter = Inter({ subsets: ['latin'] })

// Importamos el componente Navbar
import Navbar from '../components/Navbar.jsx';

export const metadata = {
  title: 'Practica Final',                 
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        {/* Establecemos nuestro favicon */}
        <link rel="icon" href="/favicon.ico" />
      </head>
      
      <body className={inter.className}>     {/* Llamamos a la fuente */}
    
        {/* Añadimos un componente Navbar */}
        <Navbar></Navbar>

        {children}
      </body>
    </html>
  )
}
